 local menuce82ef9e96797c41655cb0aed50b727d = {
     {"KMag", "kmag -caption KMag ", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
     {"KMouseTool", "kmousetool -caption KMouseTool ", "/usr/share/icons/hicolor/16x16/apps/kmousetool.png" },
     {"KMouth", "kmouth -caption KMouth ", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
 }

 local menu27f1ed0563426e266c58e655028c8284 = {
     {"Akonaditray", "akonaditray", "/usr/share/icons/hicolor/22x22/apps/akonaditray.png" },
     {"Ark", "ark -caption Ark ", "/usr/share/icons/hicolor/16x16/apps/ark.png" },
     {"Assistente de importação do KMail", "importwizard", "/usr/share/icons/hicolor/64x64/apps/kontact-import-wizard.png" },
     {"Filelight", "filelight ", "/usr/share/icons/hicolor/16x16/apps/filelight.png" },
     {"HP Device Manager", "hp-toolbox", "///usr/share/hplip/data/images/128x128/hp_logo.png" },
     {"KAlarm", "kalarm -caption KAlarm ", "/usr/share/icons/hicolor/16x16/apps/kalarm.png" },
     {"KCalc", "kcalc -caption KCalc"},
     {"KCharSelect", "kcharselect -caption KCharSelect"},
     {"KFileReplace", "kfilereplace  -caption KFileReplace", "/usr/share/icons/hicolor/22x22/apps/kfilereplace.png" },
     {"KFloppy", "kfloppy -caption KFloppy", "/usr/share/icons/hicolor/16x16/apps/kfloppy.png" },
     {"KGpg", "kgpg ", "/usr/share/icons/hicolor/16x16/apps/kgpg.png" },
     {"KJots", "kjots -caption KJots", "/usr/share/icons/hicolor/16x16/apps/kjots.png" },
     {"KMag", "kmag -caption KMag ", "/usr/share/icons/hicolor/16x16/apps/kmag.png" },
     {"KMouseTool", "kmousetool -caption KMouseTool ", "/usr/share/icons/hicolor/16x16/apps/kmousetool.png" },
     {"KMouth", "kmouth -caption KMouth ", "/usr/share/icons/hicolor/16x16/apps/kmouth.png" },
     {"KNotes", "knotes", "/usr/share/icons/hicolor/16x16/apps/knotes.png" },
     {"KTeaTime", "kteatime", "/usr/share/icons/hicolor/16x16/apps/kteatime.png" },
     {"KTimeTracker", "ktimetracker", "/usr/share/icons/hicolor/16x16/apps/ktimetracker.png" },
     {"KTimer", "ktimer", "/usr/share/icons/hicolor/16x16/apps/ktimer.png" },
     {"KWrite", "kwrite "},
     {"Kate", "kate -b ", "/usr/share/icons/hicolor/16x16/apps/kate.png" },
     {"Kleopatra", "kleopatra", "/usr/share/icons/hicolor/16x16/apps/kleopatra.png" },
     {"Mapa de caracteres", "gucharmap"},
     {"Notas", "notes-mobile", "/usr/share/icons/hicolor/48x48/apps/notes-mobile.png" },
     {"Okteta", "okteta -caption Okteta ", "/usr/share/icons/hicolor/16x16/apps/okteta.png" },
     {"SCIM (Smart Common Input Method) startup", "scim -d", "///usr/share/pixmaps/scim-setup.png" },
     {"Sweeper", "sweeper"},
     {"XCA", "xca ", "/usr/share/pixmaps/xca-32x32.xpm" },
     {"compton", "compton"},
     {"gpa", "gpa", "/usr/share/pixmaps/gpa.png" },
     {"luckyBackup", "/usr/bin/luckybackup", "///usr/share/pixmaps/luckybackup.png" },
 }

 local menu5392ed125d387e4ac53b496ec76d3280 = {
     {"Artikulate", "artikulate -caption Artikulate ", "/usr/share/icons/hicolor/16x16/apps/artikulate.png" },
     {"Blinken", "blinken", "/usr/share/icons/hicolor/16x16/apps/blinken.png" },
     {"Cantor", "cantor  -caption Cantor", "/usr/share/icons/hicolor/16x16/apps/cantor.png" },
     {"Editor de temas do Pairs", "pairseditor  -caption Pairs Theme Editor", "/usr/share/icons/hicolor/16x16/apps/pairseditor.png" },
     {"KAlgebra", "kalgebra", "/usr/share/icons/hicolor/16x16/apps/kalgebra.png" },
     {"KAlgebra Móvel", "kalgebramobile", "/usr/share/icons/hicolor/16x16/apps/kalgebra.png" },
     {"KBruch", "kbruch -caption KBruch ", "/usr/share/icons/hicolor/16x16/apps/kbruch.png" },
     {"KGeography", "kgeography", "/usr/share/icons/hicolor/16x16/apps/kgeography.png" },
     {"KHangMan", "khangman -caption KHangMan ", "/usr/share/icons/hicolor/16x16/apps/khangman.png" },
     {"KLettres", "klettres -caption KLettres ", "/usr/share/icons/hicolor/16x16/apps/klettres.png" },
     {"KStars", "kstars -caption KStars ", "/usr/share/icons/hicolor/16x16/apps/kstars.png" },
     {"KTouch", "ktouch -caption KTouch ", "/usr/share/icons/hicolor/16x16/apps/ktouch.png" },
     {"KTurtle", "kturtle  -caption KTurtle", "/usr/share/icons/hicolor/16x16/apps/kturtle.png" },
     {"KWordQuiz", "kwordquiz -caption KWordQuiz ", "/usr/share/icons/hicolor/16x16/apps/kwordquiz.png" },
     {"Kalzium", "kalzium -caption Kalzium ", "/usr/share/icons/hicolor/16x16/apps/kalzium.png" },
     {"Kanagram", "kanagram", "/usr/share/icons/hicolor/16x16/apps/kanagram.png" },
     {"Kig", "kig   -caption Kig", "/usr/share/icons/hicolor/16x16/apps/kig.png" },
     {"Kiten", "kiten -caption Kiten ", "/usr/share/icons/hicolor/16x16/apps/kiten.png" },
     {"KmPlot", "kmplot", "/usr/share/icons/hicolor/16x16/apps/kmplot.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"Marble", "marble-qt ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Marble", "marble ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Marble", "marble-mobile ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Marble", "marble-touch ", "/usr/share/icons/hicolor/16x16/apps/marble.png" },
     {"Pairs", "pairs  -caption Pairs", "/usr/share/icons/hicolor/16x16/apps/pairs.png" },
     {"Parley", "parley ", "/usr/share/icons/hicolor/16x16/apps/parley.png" },
     {"Rocs", "rocs  -caption Rocs", "/usr/share/icons/hicolor/16x16/apps/rocs.png" },
     {"Step", "step -caption Step ", "/usr/share/icons/hicolor/16x16/apps/step.png" },
 }

 local menu1e8e168b1235cc357ae3f38452476237 = {
     {"Bitcoin Core", "/usr/bin/bitcoin-qt ", "/usr/share/pixmaps/bitcoin.png" },
     {"Bitcoin Core", "/usr/bin/bitcoin-qt -datadir=/media/nas/home/.bitcoin ", "/usr/share/pixmaps/bitcoin.png" },
     {"Braindump", "braindump ", "/usr/share/icons/hicolor/16x16/apps/braindump.png" },
     {"Calendário", "korganizer-mobile", "/usr/share/icons/hicolor/48x48/apps/korganizer-mobile.png" },
     {"Calligra Active", "calligraactive"},
     {"Calligra Author", "calligraauthor ", "/usr/share/icons/hicolor/16x16/apps/calligraauthor.png" },
     {"Calligra Flow", "calligraflow ", "/usr/share/icons/hicolor/16x16/apps/calligraflow.png" },
     {"Calligra Gemini", "calligragemini ", "/usr/share/icons/hicolor/16x16/apps/calligragemini.png" },
     {"Calligra Sheets", "calligrasheets ", "/usr/share/icons/hicolor/16x16/apps/calligrasheets.png" },
     {"Calligra Stage", "calligrastage ", "/usr/share/icons/hicolor/16x16/apps/calligrastage.png" },
     {"Calligra Words", "calligrawords ", "/usr/share/icons/hicolor/16x16/apps/calligrawords.png" },
     {"Contatos", "kaddressbook-mobile", "/usr/share/icons/hicolor/48x48/apps/kaddressbook-mobile.png" },
     {"Edit E-book", "ebook-edit --detach ", "/usr/share/icons/hicolor/256x256/apps/calibre-ebook-edit.png" },
     {"Editor de temas de cabeçalho do KMail", "headerthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"Editor de temas de contatos", "contactthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kaddressbook.png" },
     {"Editor do Sieve", "sieveeditor", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"Exportação das Definições PIM", "pimsettingexporter"},
     {"Gerenciador de Serviços em Nuvem", "storageservicemanager", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KAddressBook", "kaddressbook ", "/usr/share/icons/hicolor/16x16/apps/kaddressbook.png" },
     {"KMail", "kmail -caption KMail ", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KOrganizer", "korganizer ", "/usr/share/icons/hicolor/16x16/apps/korganizer.png" },
     {"KTimeTracker", "ktimetracker", "/usr/share/icons/hicolor/16x16/apps/ktimetracker.png" },
     {"KTnef", "ktnef ", "/usr/share/icons/hicolor/48x48/apps/ktnef.png" },
     {"Karbon", "karbon ", "/usr/share/icons/hicolor/16x16/apps/calligrakarbon.png" },
     {"Kexi", "kexi", "/usr/share/icons/hicolor/16x16/apps/calligrakexi.png" },
     {"Kontact", "kontact", "/usr/share/icons/hicolor/16x16/apps/kontact.png" },
     {"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
     {"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"LibreOffice Extension Manager", "unopkg gui ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
     {"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
     {"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
     {"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
     {"Lokalize", "lokalize  -caption Lokalize", "/usr/share/icons/hicolor/32x32/apps/lokalize.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Plan", "calligraplan ", "/usr/share/icons/hicolor/16x16/apps/calligraplan.png" },
     {"Tarefas", "tasks-mobile", "/usr/share/icons/hicolor/48x48/apps/tasks-mobile.png" },
     {"Tratamento de pacotes de trabalho do Plan", "calligraplanwork ", "/usr/share/icons/hicolor/16x16/apps/calligraplanwork.png" },
     {"calibre", "calibre --detach ", "/usr/share/icons/hicolor/256x256/apps/calibre-gui.png" },
 }

 local menuaee21f5228fb7931758d996659241ec4 = {
     {"BleachBit", "bleachbit", "/usr/share/pixmaps/bleachbit.png" },
     {"Cópia de segurança do Nepomuk", "nepomukbackup"},
     {"Dolphin", "dolphin  -caption Dolphin "},
     {"Editor do dconf", "dconf-editor", "/usr/share/icons/hicolor/16x16/apps/dconf-editor.png" },
     {"Gerenciador de partições do KDE", "xdg_menu_su partitionmanager", "/usr/share/icons/hicolor/16x16/apps/partitionmanager.png" },
     {"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
     {"K3b", "k3b ", "/usr/share/icons/hicolor/16x16/apps/k3b.png" },
     {"KDiskFree", "kdf -caption KDiskFree", "/usr/share/icons/hicolor/16x16/apps/kdf.png" },
     {"KSysGuard", "ksysguard "},
     {"KSystemLog", "xdg_menu_su ksystemlog  -caption KSystemLog"},
     {"KUser", "xdg_menu_su kuser  -caption KUser", "/usr/share/icons/hicolor/16x16/apps/kuser.png" },
     {"KWalletManager", "kwalletmanager ", "/usr/share/icons/hicolor/16x16/apps/kwalletmanager.png" },
     {"Konsole", "konsole"},
     {"Krfb", "krfb -caption Krfb "},
     {"KwikDisk", "kwikdisk -caption KwikDisk", "/usr/share/icons/hicolor/16x16/apps/kwikdisk.png" },
     {"Limpeza do Nepomuk", "nepomukcleaner"},
     {"Manage Printing", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
     {"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/apps/virtualbox.png" },
     {"Terminator", "terminator", "/usr/share/icons/hicolor/16x16/apps/terminator.png" },
     {"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Wine Launcher Creator", "\"/usr/local/bin/wlcreator.py\""},
     {"Wireshark", "wireshark ", "/usr/share/icons/hicolor/16x16/apps/wireshark.png" },
     {"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
     {"Yakuake", "yakuake", "/usr/share/icons/hicolor/16x16/apps/yakuake.png" },
     {"luckyBackup (super usuário)", "su-to-root -X -c /usr/bin/luckybackup", "///usr/share/pixmaps/luckybackup.png" },
 }

 local menue2fa0f6ba17f6bf3d1bf1dbed5a1c5b2 = {
     {"E-book Viewer", "ebook-viewer --detach ", "/usr/share/icons/hicolor/256x256/apps/calibre-viewer.png" },
     {"Geeqie", "geeqie -r ", "/usr/share/pixmaps/geeqie.png" },
     {"Gwenview", "gwenview  -caption Gwenview ", "/usr/share/icons/hicolor/16x16/apps/gwenview.png" },
     {"KColorChooser", "kcolorchooser", "/usr/share/icons/hicolor/16x16/apps/kcolorchooser.png" },
     {"KRuler", "kruler", "/usr/share/icons/hicolor/16x16/apps/kruler.png" },
     {"KSnapshot", "ksnapshot -caption KSnapshot", "/usr/share/icons/hicolor/16x16/apps/ksnapshot.png" },
     {"Karbon", "karbon ", "/usr/share/icons/hicolor/16x16/apps/calligrakarbon.png" },
     {"KolourPaint", "kolourpaint ", "/usr/share/icons/hicolor/16x16/apps/kolourpaint.png" },
     {"Krita", "krita ", "/usr/share/icons/hicolor/16x16/apps/calligrakrita.png" },
     {"Krita Sketch", "kritasketch", "/usr/share/icons/hicolor/16x16/apps/calligrakrita.png" },
     {"LRF Viewer", "lrfviewer ", "/usr/share/icons/hicolor/256x256/apps/calibre-viewer.png" },
     {"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
     {"Okular", "okular   -caption Okular", "/usr/share/icons/hicolor/16x16/apps/okular.png" },
     {"Programa de manipulação de imagem do GNU", "gimp-2.8 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
     {"Skanlite", "skanlite -caption Skanlite "},
     {"X PDF", "xpdf", "/usr/share/pixmaps/xpdfIcon.xpm" },
     {"XSane", "xsane", "/usr/share/pixmaps/xsane.xpm" },
 }

 local menuc8205c7636e728d448c2774e6a4a944b = {
     {"Akregator", "akregator   -caption Akregator", "/usr/share/icons/hicolor/16x16/apps/akregator.png" },
     {"Armory", "python /usr/lib64/python2.7/site-packages/armory/ArmoryQt.py", "/usr/share/pixmaps/armoryicon.png" },
     {"Armory (Offline-mode)", "python /usr/lib64/python2.7/site-packages/armory/ArmoryQt.py --offline", "/usr/share/pixmaps/armoryicon.png" },
     {"Armory (Testnet)", "python /usr/lib64/python2.7/site-packages/armory/ArmoryQt.py --testnet", "/usr/share/pixmaps/armorytestneticon.png" },
     {"Bitcoin Core", "/usr/bin/bitcoin-qt ", "/usr/share/pixmaps/bitcoin.png" },
     {"Bitcoin Core", "/usr/bin/bitcoin-qt -datadir=/media/nas/home/.bitcoin ", "/usr/share/pixmaps/bitcoin.png" },
     {"BlueDevil", "bluedevil-monolithic"},
     {"Choqok", "choqok  -caption Choqok", "/usr/share/icons/hicolor/16x16/apps/choqok.png" },
     {"Chromium", "chromium ", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"Chromium", "chromium --incognito \s", "/usr/share/icons/hicolor/16x16/apps/chromium.png" },
     {"CloudStation", "/home/deny/.CloudStation/CloudStation-app/package/start-stop start"},
     {"CloudStation Uninstaller", "/home/deny/.CloudStation/CloudStation-app/package/uninstall"},
     {"DBPedia References", "krubyapplication dbpedia_references/dbpedia_references.rb"},
     {"Dell SonicWALL NetExtender", "/usr/bin/netExtenderGui", "///usr/share/netExtender/icons/nx48.xpm" },
     {"Dropbox", "dropbox start -i", "/usr/share/icons/hicolor/16x16/apps/dropbox.png" },
     {"E-mail", "kmail-mobile", "/usr/share/icons/hicolor/48x48/apps/kmail-mobile.png" },
     {"Editor de temas de cabeçalho do KMail", "headerthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"Editor de temas de contatos", "contactthemeeditor", "/usr/share/icons/hicolor/16x16/apps/kaddressbook.png" },
     {"Editor do Sieve", "sieveeditor", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"Electrum Bitcoin Wallet", "electrum ", "/usr/share/pixmaps/electrum.png" },
     {"Exportação das Definições PIM", "pimsettingexporter"},
     {"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
     {"Firefox", "firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
     {"Gerenciador de Serviços em Nuvem", "storageservicemanager", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KGet", "kget -caption KGet  ", "/usr/share/icons/hicolor/16x16/apps/kget.png" },
     {"KMail", "kmail -caption KMail ", "/usr/share/icons/hicolor/16x16/apps/kmail.png" },
     {"KNode", "knode -caption KNode", "/usr/share/icons/hicolor/16x16/apps/knode.png" },
     {"KPPP", "kppp", "/usr/share/icons/hicolor/16x16/apps/kppp.png" },
     {"KRDC", "krdc -caption KRDC "},
     {"KTnef", "ktnef ", "/usr/share/icons/hicolor/48x48/apps/ktnef.png" },
     {"KTorrent", "ktorrent  -caption \"KTorrent\" ", "/usr/share/icons/hicolor/16x16/apps/ktorrent.png" },
     {"Konqueror", "kfmclient openProfile webbrowsing", "/usr/share/icons/hicolor/16x16/apps/konqueror.png" },
     {"Konversation", "konversation -caption Konversation ", "/usr/share/icons/hicolor/16x16/apps/konversation.png" },
     {"Kopete", "kopete -caption Kopete ", "/usr/share/icons/hicolor/16x16/apps/kopete.png" },
     {"Krfb", "krfb -caption Krfb "},
     {"Leitor de Notícias Pan", "pan", "/usr/share/pixmaps/pan.png" },
     {"Lutris", "lutris ", "/usr/share/pixmaps/lutris.png" },
     {"Mensageiro da Internet Pidgin", "pidgin", "/usr/share/icons/hicolor/16x16/apps/pidgin.png" },
     {"Remmina", "remmina", "/usr/share/icons/hicolor/16x16/apps/remmina.png" },
     {"SeaMonkey", "/usr/bin/seamonkey", "///usr/share/pixmaps/seamonkey-icon.png" },
     {"SeaMonkey", "/usr/bin/seamonkey --private", "///usr/share/pixmaps/seamonkey-icon.png" },
     {"SeaMonkey Mail", "/usr/bin/seamonkey -mail", "///usr/share/pixmaps/seamonkey-mail-icon.png" },
     {"Synology Cloud Station", "synology-cloud-station start", "///opt/Synology/CloudStation/images/ico_72_cloud_station.png" },
     {"Telegram Desktop", "/home/deny/Downloads/Telegram/Telegram -- ", "///home/deny/.TelegramDesktop/tdata/icon.png" },
     {"Thunderbird", "thunderbird", "///usr/share/pixmaps/thunderbird.png" },
     {"XChat IRC", "xchat", "/usr/share/pixmaps/xchat.png" },
     {"Zenmap", "zenmap ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"Zenmap (as root)", "/usr/share/zenmap/su-to-zenmap.sh ", "///usr/share/zenmap/pixmaps/zenmap.png" },
     {"gFTP", "gftp ", "/usr/share/icons/hicolor/16x16/apps/gftp.png" },
     {"wpa_gui", "kdesu wpa_gui", "/usr/share/pixmaps/wpa_gui.png" },
 }

 local menu9934b410ae21278836151c0ae306665b = {
     {"AMOR", "amor", "/usr/share/icons/hicolor/16x16/apps/amor.png" },
     {"Batalha Naval", "knavalbattle -caption Naval Battle ", "/usr/share/icons/hicolor/16x16/apps/knavalbattle.png" },
     {"Blinken", "blinken", "/usr/share/icons/hicolor/16x16/apps/blinken.png" },
     {"Bomber", "bomber -caption Bomber", "/usr/share/icons/hicolor/32x32/apps/bomber.png" },
     {"Bovo", "bovo -caption Bovo", "/usr/share/icons/hicolor/16x16/apps/bovo.png" },
     {"Editor de temas do Pairs", "pairseditor  -caption Pairs Theme Editor", "/usr/share/icons/hicolor/16x16/apps/pairseditor.png" },
     {"Editor de visuais do KsirK", "ksirkskineditor -caption KsirK Skin Editor "},
     {"Granatier", "granatier", "/usr/share/icons/hicolor/16x16/apps/granatier.png" },
     {"Homem-Batata", "ktuberling -caption Potato Guy ", "/usr/share/icons/hicolor/16x16/apps/ktuberling.png" },
     {"KAtomic", "katomic -caption KAtomic", "/usr/share/icons/hicolor/16x16/apps/katomic.png" },
     {"KBlackBox", "kblackbox -caption KBlackBox", "/usr/share/icons/hicolor/16x16/apps/kblackbox.png" },
     {"KBlocks", "kblocks -caption KBlocks", "/usr/share/icons/hicolor/16x16/apps/kblocks.png" },
     {"KBounce", "kbounce -caption KBounce", "/usr/share/icons/hicolor/16x16/apps/kbounce.png" },
     {"KBreakOut", "kbreakout -caption KBreakOut", "/usr/share/icons/hicolor/16x16/apps/kbreakout.png" },
     {"KDiamond", "kdiamond -caption KDiamond", "/usr/share/icons/hicolor/16x16/apps/kdiamond.png" },
     {"KFourInLine", "kfourinline", "/usr/share/icons/hicolor/16x16/apps/kfourinline.png" },
     {"KGoldrunner", "kgoldrunner", "/usr/share/icons/hicolor/16x16/apps/kgoldrunner.png" },
     {"KHangMan", "khangman -caption KHangMan ", "/usr/share/icons/hicolor/16x16/apps/khangman.png" },
     {"KJumpingCube", "kjumpingcube -caption KJumpingCube", "/usr/share/icons/hicolor/16x16/apps/kjumpingcube.png" },
     {"KMahjongg", "kmahjongg -caption KMahjongg", "/usr/share/icons/hicolor/16x16/apps/kmahjongg.png" },
     {"KMines", "kmines -caption KMines", "/usr/share/icons/hicolor/16x16/apps/kmines.png" },
     {"KNetWalk", "knetwalk -caption KNetWalk", "/usr/share/icons/hicolor/16x16/apps/knetwalk.png" },
     {"KPatience", "kpat -caption KPatience", "/usr/share/icons/hicolor/16x16/apps/kpat.png" },
     {"KReversi", "kreversi -caption KReversi", "/usr/share/icons/hicolor/16x16/apps/kreversi.png" },
     {"KSnake", "ktron -snake -caption KSnake ", "/usr/share/icons/hicolor/16x16/apps/kdesnake.png" },
     {"KSnakeDuel", "ktron -caption KSnakeDuel ", "/usr/share/icons/hicolor/16x16/apps/ktron.png" },
     {"KSpaceDuel", "kspaceduel -caption KSpaceDuel", "/usr/share/icons/hicolor/16x16/apps/kspaceduel.png" },
     {"KSquares", "ksquares  -caption KSquares", "/usr/share/icons/hicolor/16x16/apps/ksquares.png" },
     {"KSudoku", "ksudoku  -caption KSudoku", "/usr/share/icons/hicolor/16x16/apps/ksudoku.png" },
     {"Kajongg", "kajongg", "/usr/share/icons/hicolor/16x16/apps/kajongg.png" },
     {"Kanagram", "kanagram", "/usr/share/icons/hicolor/16x16/apps/kanagram.png" },
     {"Kapman", "kapman", "/usr/share/icons/hicolor/16x16/apps/kapman.png" },
     {"Kigo", "kigo  -caption Kigo", "/usr/share/icons/hicolor/16x16/apps/kigo.png" },
     {"Killbots", "killbots -caption Killbots", "/usr/share/icons/hicolor/16x16/apps/killbots.png" },
     {"Kiriki", "kiriki -caption Kiriki", "/usr/share/icons/hicolor/16x16/apps/kiriki.png" },
     {"Klickety", "klickety -caption Klickety", "/usr/share/icons/hicolor/16x16/apps/klickety.png" },
     {"Kolf", "kolf ", "/usr/share/icons/hicolor/16x16/apps/kolf.png" },
     {"Kollision", "kollision", "/usr/share/icons/hicolor/16x16/apps/kollision.png" },
     {"Kolor Lines", "klines -caption Kolor Lines", "/usr/share/icons/hicolor/16x16/apps/klines.png" },
     {"Konquest", "konquest -caption Konquest", "/usr/share/icons/hicolor/16x16/apps/konquest.png" },
     {"KsirK", "ksirk -caption KsirK ", "/usr/share/icons/hicolor/16x16/apps/ksirk.png" },
     {"Kubrick", "kubrick", "/usr/share/icons/hicolor/16x16/apps/kubrick.png" },
     {"LSkat", "lskat", "/usr/share/icons/hicolor/16x16/apps/lskat.png" },
     {"Lutris", "lutris ", "/usr/share/pixmaps/lutris.png" },
     {"Pairs", "pairs  -caption Pairs", "/usr/share/icons/hicolor/16x16/apps/pairs.png" },
     {"Palapeli", "palapeli", "/usr/share/icons/hicolor/16x16/apps/palapeli.png" },
     {"SameGame", "klickety --KSameMode -caption SameGame", "/usr/share/icons/hicolor/16x16/apps/ksame.png" },
     {"Shisen-Sho", "kshisen -caption Shisen-Sho", "/usr/share/icons/hicolor/16x16/apps/kshisen.png" },
     {"XaoS", "xaos", "/usr/share/pixmaps/xaos.png" },
     {"Xboard", "xboard", "/usr/share/icons/hicolor/48x48/apps/xboard.png" },
     {"eboard", "eboard", "///usr/share/pixmaps/chess.png" },
     {"openMSX", "openmsx", "/usr/share/pixmaps/openmsx.png" },
     {"openMSX Catapult", "catapult", "/usr/share/pixmaps/catapult.xpm" },
     {"openMSX Catapult", "/dev/shm/package-openmsx-catapult/opt/openMSX-Catapult/bin/catapult"},
     {"picmi", "picmi", "/usr/share/icons/hicolor/16x16/apps/picmi.png" },
 }

 local menud35651cdbe370767cefd2e5d398a1dd5 = {
     {"Anjuta", "anjuta ", "/usr/share/icons/hicolor/16x16/apps/anjuta.png" },
     {"CMake", "cmake-gui ", "/usr/share/pixmaps/CMakeSetup32.png" },
     {"Cervisia", "cervisia -caption Cervisia  ", "/usr/share/icons/hicolor/16x16/apps/cervisia.png" },
     {"Console do Akonadi", "akonadiconsole", "/usr/share/icons/hicolor/16x16/apps/akonadiconsole.png" },
     {"Data Display Debugger", "ddd", "/usr/share/pixmaps/ddd.png" },
     {"Emacs", "emacs ", "/usr/share/icons/hicolor/16x16/apps/emacs.png" },
     {"Glade", "glade ", "/usr/share/icons/hicolor/16x16/apps/glade.png" },
     {"Glade", "glade-3 ", "/usr/share/icons/hicolor/16x16/apps/glade-3.png" },
     {"KAppTemplate", "kapptemplate", "/usr/share/icons/hicolor/16x16/apps/kapptemplate.png" },
     {"KCachegrind", "kcachegrind -caption KCachegrind ", "/usr/share/icons/hicolor/32x32/apps/kcachegrind.png" },
     {"KDevelop 4", "kdevelop ", "/usr/share/icons/hicolor/16x16/apps/kdevelop.png" },
     {"KDevelop 4 (selecionar uma sessão)", "kdevelop --ps", "/usr/share/icons/hicolor/16x16/apps/kdevelop.png" },
     {"KImageMapEditor", "kimagemapeditor -caption KImageMapEditor ", "/usr/share/icons/hicolor/16x16/apps/kimagemapeditor.png" },
     {"KLinkStatus", "klinkstatus   -caption KLinkStatus", "/usr/share/icons/hicolor/16x16/apps/klinkstatus.png" },
     {"KUIViewer", "kuiviewer -caption KUIViewer", "/usr/share/icons/hicolor/16x16/apps/kuiviewer.png" },
     {"Kompare", "kompare -caption Kompare -o ", "/usr/share/icons/hicolor/16x16/apps/kompare.png" },
     {"Lokalize", "lokalize  -caption Lokalize", "/usr/share/icons/hicolor/32x32/apps/lokalize.png" },
     {"Navegador do banco de dados", "gda-browser-5.0", "/usr/share/pixmaps/gda-browser-5.0.png" },
     {"OpenJDK Monitoring & Management Console", "jconsole", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"OpenJDK Policy Tool", "policytool", "/usr/share/icons/hicolor/16x16/apps/java.png" },
     {"PyAlaMode", "pyalamode", "/usr/share/icons/hicolor/16x16/apps/PyCrust.png" },
     {"PyCrust", "pycrust", "/usr/share/icons/hicolor/16x16/apps/PyCrust.png" },
     {"PyShell", "pyshell", "/usr/share/icons/hicolor/16x16/apps/PyCrust.png" },
     {"PySlices", "pyslices", "/usr/share/icons/hicolor/16x16/apps/PySlices.png" },
     {"PySlicesShell", "pysliceshell", "/usr/share/icons/hicolor/16x16/apps/PySlices.png" },
     {"Qt4 Assistant ", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
     {"Qt4 Designer", "designer", "/usr/share/icons/hicolor/128x128/apps/designer.png" },
     {"Qt4 Linguist ", "linguist", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
     {"Qt5 Assistant", "assistant-qt5 -qt=5"},
     {"Qt5 Designer", "designer-qt5 -qt=5"},
     {"Qt5 Linguist", "linguist-qt5 -qt=5"},
     {"Qt5 QDbusViewer", "qdbusviewer-qt5"},
     {"Umbrello", "umbrello  -caption Umbrello", "/usr/share/icons/hicolor/16x16/apps/umbrello.png" },
     {"XRCed", "xrced", "/usr/share/icons/hicolor/16x16/apps/XRCed.png" },
     {"distcc monitor", "distccmon-gnome"},
     {"pgAdmin III", "/usr/bin/pgadmin3", "///usr/share/pixmaps/pgAdmin3.png" },
 }

 local menub199120cd099b92c24c1b9fb15970f52 = {
     {"AMZ Downloader", "amzdownloader --amz "},
     {"Amarok", "amarok ", "/usr/share/icons/hicolor/16x16/apps/amarok.png" },
     {"Audacious", "audacious ", "/usr/share/icons/hicolor/48x48/apps/audacious.png" },
     {"Dragon Player", "dragon ", "/usr/share/icons/hicolor/16x16/apps/dragonplayer.png" },
     {"HandBrake", "ghb", "/usr/share/icons/hicolor/16x16/apps/hb-icon.png" },
     {"JuK", "juk -caption JuK ", "/usr/share/icons/hicolor/16x16/apps/juk.png" },
     {"K3b", "k3b ", "/usr/share/icons/hicolor/16x16/apps/k3b.png" },
     {"KAudioCreator", "kaudiocreator", "/usr/share/icons/hicolor/16x16/apps/kaudiocreator.png" },
     {"KPlayer", "kplayer -- ", "/usr/share/icons/hicolor/16x16/apps/kplayer.png" },
     {"Kdenlive", "kdenlive  -caption Kdenlive ", "/usr/share/icons/hicolor/32x32/apps/kdenlive.png" },
     {"MPlayer", "gmplayer ", "/usr/share/icons/hicolor/16x16/apps/mplayer.png" },
     {"QjackCtl", "/usr/bin/qjackctl", "/usr/share/icons/hicolor/32x32/apps/qjackctl.png" },
     {"Reprodutor de Mídias VLC", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
     {"SimpleScreenRecorder", "simplescreenrecorder --logfile", "/usr/share/icons/hicolor/256x256/apps/simplescreenrecorder.png" },
     {"Utilitário de teste V4L2", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
     {"XMMS", "xmms ", "/usr/share/pixmaps/xmms.png" },
     {"gtkpod", "gtkpod", "/usr/share/icons/hicolor/16x16/apps/gtkpod.png" },
     {"qt-recordMyDesktop", "qt-recordMyDesktop", "/usr/share/pixmaps/qt-recordmydesktop.png" },
     {"traGtor", "tragtor ", "///usr/share/pixmaps/tragtor.svg" },
     {"xine", "xine ", "/usr/share/icons/hicolor/16x16/apps/xine.png" },
 }

xdgmenu = { theme = { height = 16, width = 300 },
    {"Acessibilidade", menuce82ef9e96797c41655cb0aed50b727d},
    {"Acessórios", menu27f1ed0563426e266c58e655028c8284},
    {"Educação", menu5392ed125d387e4ac53b496ec76d3280},
    {"Escritório", menu1e8e168b1235cc357ae3f38452476237},
    {"Ferramentas do Sistema", menuaee21f5228fb7931758d996659241ec4},
    {"Gráficos", menue2fa0f6ba17f6bf3d1bf1dbed5a1c5b2},
    {"Internet", menuc8205c7636e728d448c2774e6a4a944b},
    {"Jogos", menu9934b410ae21278836151c0ae306665b},
    {"Programação", menud35651cdbe370767cefd2e5d398a1dd5},
    {"Som e Vídeo", menub199120cd099b92c24c1b9fb15970f52},
}

