#!/bin/sh
locale=$( echo $1 | cut -d "_" -f1 )
if [ -n "$locale" ]; then
  if [ "pt" = "$locale" ]; then
    echo "* Disponível exclusivamente neste tema."
    echo
    echo "<span color=\"#508ED8\">Nota:</span> Outras funções estão disponíveis via KDE."
    echo "      Ver configurações do KDE."
  fi
else
  echo "* available only in this theme."
  echo
  echo "<span color=\"#508ED8\">Note:</span> Other functions are available via KDE."
  echo "      See KDE configuration."
fi

